name: Blog Convert & Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  #this is required by sitemap generator
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
      
      - run: hugo
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: public
          path: public
      - name: Upload to Webhost
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: www184.your-server.de
          username: ${{ secrets.HETZNER_FTP_USR }}
          password: ${{ secrets.HETZNER_FTP_PWD }}
          protocol: "ftps"
          local-dir: "./public/"
          server-dir: "./blog/"
          overwrite: true
