name: Blog Convert & Publish

on:
  push:
    branches:
      - master
      - feature-*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - name: Install npm dependencies
        run: npm --prefix ./.github/scripts/ install
      - name: Convert MD to HTML
        run: node ./.github/scripts/convert.js
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
      - name: Upload to J-CX11
        uses: appleboy/scp-action@master
        with:
          host: j-cx11-web.cloud.julian-lemmerich.de
          username: ghactions
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "dist/*"
          target: "~/blog"
          overwrite: true
